sudo: required
language: go
go: 1.8.1

addons:
  hosts:
    - esi.tech.ccp.is

services:
  - docker
  - redis-server
  - mysql

before_install:
  - docker pull antihax/mock-esi
  - docker run -d -p 127.0.0.1:8080:8080 antihax/mock-esi
  - docker ps -a
  - mysql -e "CREATE DATABASE eve"
  - unzip ./sql/eve.zip -d ./sql/
  - mysql -Deve < ./sql/eve.sql
  - mysql < ./sql/evedata.sql

install:
  - go get -u github.com/antihax/evedata
  - go build evedata-server.go
  - docker build -t antihax/evedata .

script:
  - docker run --net="host" -e CODECOV_TOKEN="$CODECOV_TOKEN" --entrypoint=/go/src/github.com/antihax/evedata/dockerTest.sh --name evedata_test antihax/evedata 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push antihax/evedata;
    fi