apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-axiom
  namespace: evedata
spec:
  replicas: 5
  template:
    metadata:
      name: evedata-axiom
      labels:
        app: axiom
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - axiom
              - key: database
                operator: In
                values:
                - mysql                   
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-axiom
        image: antihax/eve-axiom
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: axiom
  namespace: evedata
spec:
  selector:
    app: axiom
  ports:
  - name: axiom
    protocol: TCP
    port: 3005
    targetPort: 3005
