apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: evedata
spec:
  selector:
    app: mailserver
  ports:
  - name: IMAP
    protocol: TCP
    port: 993
    targetPort: 993
    nodePort: 32005
  - name: SMTP
    protocol: TCP
    port: 465
    targetPort: 465
    nodePort: 32006
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-mailserver
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-mailserver
      labels:
        app: mailserver
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mailserver
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-mailserver
        image: antihax/evedata-mailserver
        imagePullPolicy: Always
        env:
        - name: ESI_SECRET_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: secret-tokenstore
        - name: ESI_CLIENTID_TOKENSTORE
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: clientID-tokenstore
        ports:
        - containerPort: 3000
        - containerPort: 465
        - containerPort: 993
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory