apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: evedata
type: Opaque
data:
  password: BASE64PASSWORD=
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-password
  namespace: evedata
type: Opaque
data:
  sqlauth: BASE64PASSWORD=
---
apiVersion: v1
kind: Secret
metadata:
  name: esi-secret
  namespace: evedata
type: Opaque
data:
  refreshKey: BASE64REFRESHKEY=
  secret: BASE64SECRET=
  clientID: BASE64CLIENTID=
  secret-tokenserver: BASE64SECRET=
  clientID-tokenserver: BASE64CLIENTID=
